POINTS = 2 ** 16
ITERATIONS = 2 ** 5
ESCAPE_RADIUS_SQUARED = 2.0 ** 2

DOMAIN_SIZE = 4.0
DOMAIN_RADIUS = DOMAIN_SIZE / 2.0

REGION_COUNT = 512
REGION_SIZE = DOMAIN_SIZE / REGION_COUNT

FRAME_SIZE = 1000
FRAME_COUNT = 128
