DEBUG_FRAME = True
DEBUG_BORDER = False
DEBUG_INTERVAL = 1

POINTS = 2 ** 16
ITERATIONS = 2 ** 5
ESCAPE_QUADRANCE = 2.0 ** 2

DOMAIN_SIZE = 4.0
DOMAIN_RADIUS = DOMAIN_SIZE / 2.0

BORDER_MAP_SIZE = 512
BORDER_MAP_RADIUS = BORDER_MAP_SIZE // 2

CELL_SIZE = DOMAIN_SIZE / BORDER_MAP_SIZE
CELL_RADIUS = CELL_SIZE / 2

FRAME_SIZE = 1024
FRAME_COUNT = 64
