POINTS = 2 ** 15
ITERATIONS = 2 ** 5
ESCAPE_RADIUS_SQUARED = 2.0 ** 2

DOMAIN_SIZE = 4.0
DOMAIN_RADIUS = DOMAIN_SIZE / 2.0

REGION_COUNT = 256
REGION_SIZE = DOMAIN_SIZE / REGION_COUNT

FRAME_SIZE = 800
FRAME_COUNT = 512
